{{- range $index, $network := .Values.networks }}
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: marlowe-token-plans-{{ $network }}
spec:
  components:
    - name: marlowe-token-plans-{{ $network }}
      properties:
        image: joseluisq/static-web-server:2
        args:
          - --root
          - /client-www
          - --port
          - "8080"
          - --page-fallback
          - "/client-www/index.html"
          - --log-level
          - "info"
          - --cors-allow-origins
          - "*"
        imagePullPolicy: Always
        ports:
          - expose: true
            port: 8080
            protocol: TCP
      traits:
        - properties:
            replicas: 1
          type: scaler
        - properties:
            domains:
              - token-plans-{{ $network }}.prod.scdev.aws.iohkdev.io
            rules:
              - port: 8080
          type: https-route
        - type: init-container
          properties:
            name: load-token-plans-client
            image: ghcr.io/input-output-hk/marlowe-vesting:{{ $.Values.images.productionTag }}
            args:
              - -c
              - |
                  root="$(dirname $(readlink -f /profile/index.html))"
                  cp -a $root/* /share/marlowe-token-plans/static
                  cat > /share/marlowe-token-plans/static/config.json <<EOF
                  {
                    "marloweWebServerUrl": "https://marlowe-runtime-{{ $network }}-web.demo.scdev.aws.iohkdev.io"
                  }
                  EOF
            mountName: client-www
            initMountPath: /share/marlowe-token-plans/static
            appMountPath: /client-www
      type: webservice
  policies:
    - name: marlowe-token-plans-staging
      properties:
        clusters:
          - local
        namespace: marlowe-staging
      type: topology

    - name: marlowe-token-plans
      properties:
        clusters:
          - local
        namespace: marlowe-production
      type: topology

    - name: staging-override
      type: override
      properties:
        components:
          - name: marlowe-token-plans-{{ $network }}
            properties:
              image: joseluisq/static-web-server:2
              args:
                - --root
                - /client-www
                - --port
                - "8080"
                - --page-fallback
                - "/client-www/index.html"
                - --log-level
                - "info"
                - --cors-allow-origins
                - "*"
              imagePullPolicy: Always
              ports:
                - expose: true
                  port: 8080
                  protocol: TCP
            traits:
              - properties:
                  replicas: 1
                type: scaler
              - properties:
                  domains:
                    - token-plans-{{ $network }}.scdev.aws.iohkdev.io
                  rules:
                    - port: 8080
                type: https-route
              - type: init-container
                properties:
                  name: load-token-plans-client
                  image: ghcr.io/input-output-hk/marlowe-vesting:{{ $.Values.images.stagingTag }}
                  args:
                    - -c
                    - |
                        root="$(dirname $(readlink -f /profile/index.html))"
                        cp -a $root/* /share/marlowe-token-plans/static
                        cat > /share/marlowe-token-plans/static/config.json <<EOF
                        {
                          "marloweWebServerUrl": "https://marlowe-runtime-{{ $network }}-web.demo.scdev.aws.iohkdev.io"
                        }
                        EOF
                  mountName: client-www
                  initMountPath: /share/marlowe-token-plans/static
                  appMountPath: /client-www
            type: webservice
  workflow:
    mode:
      steps: DAG
    steps:
      - meta:
          alias: Push staging image
        name: push-image-staging
        type: build-nix-image
        properties:
          image: ghcr.io/input-output-hk/marlowe-vesting:{{ $.Values.images.stagingTag }}
          requests:
            ephemeralStorage: 25Gi
          includedFlakeURIs:
            - "github:input-output-hk/marlowe-token-plans?ref={{ $.Values.images.stagingTag }}#marlowe-vesting"
      - meta:
          alias: Push image
        name: push-image
        type: build-nix-image
        properties:
          image: ghcr.io/input-output-hk/marlowe-vesting:{{ $.Values.images.productionTag }}
          requests:
            ephemeralStorage: 25Gi
          includedFlakeURIs:
            - "github:input-output-hk/marlowe-token-plans?ref={{ $.Values.images.productionTag }}#marlowe-vesting"
      - type: deploy
        meta:
          alias: Deploy marlowe-token-plans
        dependsOn:
          - push-image
        name: marlowe-token-plans
        properties:
          policies:
            - marlowe-token-plans
      - type: deploy
        meta:
          alias: Deploy marlowe-token-plans to staging
        dependsOn:
          - push-image-staging
        name: marlowe-token-plans-staging
        properties:
          policies:
            - marlowe-token-plans-staging
            - staging-override
{{- end }}
